### ISSUE TITLE
Ordre des couleurs R et G pour les Led WS2812B

### ISSUE THREAD

**Issue by Champal** [hallard/remora_soft#15]
Bonjour, 

Pour les WS2812[B] l'ordre des couleurs est GRB et non pas RGB.
https://github.com/Makuna/NeoPixelBus/wiki/NeoPixelBus-object#neogrbfeature

Il faut remplacer `NeoRgbFeature` par  `NeoGrbFeature` ligne 246 de remora.h
https://github.com/hallard/remora_soft/blob/master/remora.h#L246

**Comment by hallard** [comment]
@Champal 
Tout à fait, ça dépend des fournisseurs, parfois je reçois des RGB d'autres des GRB et je ne parle pas des nouvelles RGBW ou GRBW, donc oui il faut parfois ajuster le code ;-)
