### ISSUE TITLE
Remontée info HC/HP via PTEC sous Jeedom

### ISSUE THREAD

**Issue by Gis70** [hallard/remora_soft#20]
Bonjour,

PTEC remonte bien en brute sous Jeedom mais derrière ça passe directe en numeric àld string.

Je me demande si les .. que l'on voit après HC ou HP n'y sont pas pour qqch ? HC.. ?

Si tu vois une solution... Merci.

**Comment by Azema** [comment]
Les données envoyées par la Remora n'ont pas de type, puisqu'elles sont envoyé par le biais d'une URL. La conversion vers un type ou un autre est à la charge du système qui reçoit les données. Le problème se situe donc sur ton système domotique.

**Comment by Azema** [comment]
Aucun retour de la part de @Gis70 , donc on ferme le ticket
