### ISSUE TITLE
Reboot de l'ESP lors de l’enregistrement de la conf via le web

### ISSUE THREAD

**Issue by bronco0** [hallard/remora_soft#48]
Bonjour,

Lorsqu'on modifie les paramètres depuis l'interface web, l'ESP reboot même si on ne modifie pas les valeurs. 
C'est dû au reboot dans le code suivant :
https://github.com/hallard/remora_soft/blob/be8c7de4c568d6637425f63f1da3e2d480504e89/webserver.cpp#L887-L890
La comparaison ne peut pas être faite de cette manière, les 2 chaines ne sont pas identique.

Dans la structure config, ota_auth à une taille de 65 octets.
https://github.com/hallard/remora_soft/blob/be8c7de4c568d6637425f63f1da3e2d480504e89/config.h#L134

Si on définit le champs "Mot de passe OTA" avec pour valeur OTA_Remora
`request->getParam("ota_auth", true)->value().c_str())` 
Sa taille vaut 10 + 1 octets pour \0

Lors de la comparaison avec "==" les 2 chaines sont différente comme on peut le voir en hex :
**config.ota_auth**
```
Char = OTA_Remora
Hex = 4f 54 41 5f 52 65 6d 6f 72 61 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

**request->getParam("ota_auth", true)->value().c_str())**
```
Char = OTA_Remora
Hex = 4f 54 41 5f 52 65 6d 6f 72 61 0
```

Log sur le port série en ayant ajouté des Debug dans le code
```
===== Posted configuration
Ota changed : Reboot
OTA_Remora
old ota : 4f 54 41 5f 52 65 6d 6f 72 61 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
OTA_Remora
new ota : 4f 54 41 5f 52 65 6d 6f 72 61 
cfg_led_bright: 48
Write config OK!
```
Code modifié pour les test
```
   if (config.ota_auth != request->getParam("ota_auth", true)->value().c_str()) {
        Debugln("Ota changed : Reboot");
      
        Debugln(config.ota_auth);
        Debug("old ota : ");
        for (int i=0; i < sizeof(config.ota_auth); i++) {
          Debug(String(config.ota_auth[i], HEX)); Debug(" ");
        } 
        Debugln();
        Debugln(request->getParam("ota_auth", true)->value().c_str());
        Debug("new ota : ");
        for (int i=0; i < 10; i++) {
          Debug(String(request->getParam("ota_auth", true)->value().c_str()[i], HEX)); Debug(" ");
        } 
        Debugln();
      
        strncpy(config.ota_auth, request->getParam("ota_auth", true)->value().c_str(), CFG_PSK_SIZE );
        reboot = true;
      }
```
Pour corriger le problème j'ai utilisé strcmp qui se base sur \0 comme strncpy pour déterminer la fin de ligne.

Jon

**Comment by Azema** [comment]
PR merged
